name: Deploy HTML

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Create HTML file
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="th">
          <head>
          <meta charset="UTF-8">
          <title>My First Deploy</title>
          <style>
          body { font-family: sans-serif; text-align: center; padding: 50px; background: #f0f4f8; }
          h1 { color: #7658d1; }
          </style>
          </head>
          <body>
          <h1>Hello from GitLab CI/CD!(GitHub)</h1>
          <p>Deploy สำเร็จแล้ว</p>
          </body>
          </html>
          EOF

      - name: Deploy to Nginx
        run: |
          cp index.html /var/www/html/index.html
          echo "Deployed!"